#!/bin/bash

if [ x$1 = xSKIP ]; then
	skip=yes
	shift
fi

base=`basename $1`
out=${base}.out
./${base} > ${out}

if [ x$skip = xyes ]; then
	exit 77;
fi

ref=ref/${out}
diff -rup $out $ref || exit 1
rm $out
