#!/bin/bash

if [ x$1 = xSKIP ]; then
	skip=yes
	shift
fi

base=`basename $1`
out=${base}.out
make $out PYTHON=${PYTHON}

if [ x$skip = xyes ]; then
	exit 77;
fi

ref=ref${PYTHON_VERSION}/${out}
diff -rup $out $ref || exit 1
rm $out
